version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: keep1234
      MYSQL_DATABASE: keeplearning
      MYSQL_USER: keeplearning
      MYSQL_PASSWORD: keep1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file=/docker-entrypoint-initdb.d/init.sql
    networks:
      - java-spring-mysql-network

  java-spring:
    image: java-spring
    container_name: spring_boot_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/keeplearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: keep1234
    networks:
      - java-spring-mysql-network

volumes:
  mysql_data:
    driver: local

networks:
  java-spring-mysql-network:
    driver: bridge


# version: '3'

# services:
#   mysqldb:
#     container_name: mysqldb
#     image: mysql:latest
#     environment:
#       - MYSQL_ROOT_PASSWORD=Jameszaa123+
#       - MYSQL_DATABASE=guessnumber
#       - MYSQL_SSL_MODE=REQUIRED
#     restart: always
#     ports:
#       - 3306:3306
#     volumes:
#       - mysqldb:/var/lib/mysql



#   guessnumber-java:
#     container_name: guessnumber-java
#     image: guessnumber
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     depends_on:
#       - mysqldb    
#     ports:
#       - 80:8080
#     restart: always

# volumes:
#   mysqldb:
